[package]
name = "colinterp"
version = "0.1.0"
edition = "2021"
authors = ["Nuno David <email@ndavd.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
